In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('./data.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rank               200 non-null    int64
 1   channel_info       200 non-null    object
 2   influence_score    200 non-null    int64
 3   posts              200 non-null    object
 4   followers          200 non-null    object
 5   avg_likes          200 non-null    object
 6   60_day_eng_rate    200 non-null    object
 7   new_post_avg_like  200 non-null    object
 8   total_likes        200 non-null    object
 9   country            138 non-null    object
dtypes: int64(2), object(8)
memory usage: 15.8+ KB

In [7]:
df.memory_usage(deep=True)

Index                  128
rank                  1600
channel_info         13600
influence_score       1600
posts                12273
followers            12433
avg_likes            12384
60_day_eng_rate      12404
new_post_avg_like    12411
total_likes          12307
country              11278
dtype: int64

In [11]:
df.iloc[0]

rank                         1
channel_info         cristiano
influence_score             92
posts                     3.3k
followers               475.8m
avg_likes                 8.7m
60_day_eng_rate          1.39%
new_post_avg_like         6.5m
total_likes              29.0b
country                  Spain
Name: 0, dtype: object

In [14]:
df.sort_values('channel_info')

,rank,channel_info,influence_score,posts,followers,avg_likes,60_day_eng_rate,new_post_avg_like,total_likes,country
95,96,433,79,10.3k,51.2m,863.2k,1.52%,774.2k,8.9b,Netherlands
117,118,5-Minute Crafts GIRLY,85,10.0k,46.5m,157.0k,0.03%,12.4k,1.6b,United States
73,74,9gag,86,10.0k,58.1m,672.6k,0.44%,248.6k,6.7b,United States
39,40,Shakira,88,2.0k,76.1m,975.1k,0.41%,304.7k,1.9b,NaN
148,149,addisonraee,85,0.30k,40.1m,3.1m,2.49%,994.4k,957.9m,NaN
...,...,...,...,...,...,...,...,...,...,...
153,154,worldstar,78,11.6k,39.2m,157.4k,0.23%,84.4k,1.8b,United States
83,84,zacefron,86,0.66k,54.5m,2.3m,8.18%,4.4m,1.5b,United States
118,119,zayn,82,0.16k,46.5m,4.7m,8.81%,4.0m,773.5m,United States
22,23,zendaya,87,3.5k,150.7m,5.8m,3.17%,4.8m,20.6b,United States
193,194,zidane,41,0.37k,33.5m,1.1m,1.61%,532.7k,391.9m,France